## 자료형 ndarray

In [7]:
import numpy as np
np.__version__

'1.26.4'

In [5]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [6]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [7]:
a @ b

array([[12,  6],
       [12,  6]])

In [8]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [9]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

### 배열 함수와 범용함수

In [8]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [9]:
a.sum()

46

In [10]:
a.sum(axis=0)

array([16, 30])

In [11]:
a.sum(axis=1)

array([30, 13,  3])

In [13]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [14]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [15]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [16]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [17]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [22]:
import numpy as np

a = np.array([1, 4, 9])
np.sqrt(a)

array([1., 2., 3.])

In [23]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [24]:
import numpy as np

a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [25]:
b= np.full_like(a, 2)
b

array([2, 2, 2])

In [26]:
np.add(a, b)


array([ 3,  6, 11])

In [27]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [28]:
np.power(a, b)

array([ 1, 16, 81])

### 배열첨자와 슬라이싱

In [29]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [30]:
print(a[3])
print(a[-2])

9
64


In [31]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [32]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [33]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0], dtype=int32)

In [35]:
a[::-2]

array([81, 49, 25,  9,  1], dtype=int32)

In [37]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [39]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [40]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [41]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [44]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [45]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [46]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [47]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [48]:
a[2, 4]

16

In [49]:
a[2][4]

16

In [50]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [51]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [52]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [53]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [56]:
a[:, 1, 1]

array([ 5, 17])

In [57]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [58]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [59]:
a[1, ..., 1]

array([13, 17, 21])

In [60]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [64]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [68]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [70]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [71]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [72]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [73]:
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [74]:
c = np.arange(1, 13).reshape(2, 2, 3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
c.transpose((1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [76]:
np.transpose(c, (1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [77]:
np.transpose(c)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [79]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [80]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [81]:
y[0, 0] = 10
x

array([[10,  8,  9]])

In [82]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [83]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [84]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [85]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [86]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [87]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [88]:
org

array([  0,   1, 200,   3,   4])

In [89]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [90]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [91]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [92]:
org

array([0, 1, 2, 3, 4])

In [93]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [94]:
y = x.reshape(2, 3) # view를 반환
y

array([[0, 1, 2],
       [3, 4, 5]])

In [96]:
y.base

array([0, 1, 2, 3, 4, 5])

In [97]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [98]:
c = z.copy()
print(c.base)

None


In [99]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [100]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [101]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [102]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [103]:
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [105]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
b = a
b is a

True

In [107]:
print(id(a))
print(id(b))

1391199166768
1391199166768


In [108]:
print(b.base)

None


In [109]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [110]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [111]:
print(id(a))
print(id(v))

1391199166768
1391199172528


In [112]:
v[0, 1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [113]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])