# ch03 브로드캐스팅 

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [4]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [5]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

# Ch04 다차원 배열 결합과 분리 (~151p)

#### np.vstack(tup)

In [23]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [26]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

#### np.hstack()

In [27]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [29]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

#### np.column_stack()

In [6]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [9]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [30]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [31]:
np.hstack((x, y))

array([1, 2, 3, 5, 6, 7])

In [32]:
np.column_stack == np.hstack

False

#### np.row_stack()

In [54]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [56]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

#### np.concatenate()

In [8]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [11]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [12]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [13]:
# 1차 배열인 경우 axis=0과 동일
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [14]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [16]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [17]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [18]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [19]:
# 평면화 작업 후 연결
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

#### np.stack(함수)

In [33]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [34]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [35]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
np.stack((a,b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 3차월 배열 이해

In [38]:
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [39]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

#### np.stack 

##### axis=0

In [40]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [42]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [43]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [44]:
ax0.shape

(3, 2, 3)

##### axis=1

In [45]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [46]:
ax1.shape

(2, 3, 3)

##### axis=2

In [47]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [48]:
ax2.shape

(2, 3, 3)

##### axis=0|1|2

In [49]:
print(x, '\n')
print(y, '\n')
print(z, '\n')

[[0 1 2]
 [3 4 5]] 

[[10 11 12]
 [13 14 15]] 

[[20 21 22]
 [23 24 25]] 



In [50]:
print('np.stack((x, y, z), axis=0')
print(np.stack((x, y, z), axis=0))
print('np.stack((x, y, z), axis=1')
print(np.stack((x, y, z), axis=1))
print('np.stack((x, y, z), axis=2')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis=1
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis=2
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


##### 연산 np.stack((x, y, z), axis=2) 과정

In [51]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [53]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [58]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [59]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [60]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [61]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [62]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [63]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [65]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

#### column_stack() & hstack()

In [66]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[0, 1, 2, 5],
       [3, 4, 5, 6]])

In [67]:
np.column_stack((a, c))

array([[0, 1, 2, 5],
       [3, 4, 5, 6]])

#### row_stack() & vstack()

In [68]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [70]:
np.row_stack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [71]:
np.vstack((a ,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

#### np.c_[]

In [72]:
import numpy as np

# 2개의 1D 배열을 열 방향으로 결합
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.c_[a, b]
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [73]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [74]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [77]:
np.c_[x, y]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [78]:
np.column_stack((x ,y))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
np.c_[x, 10, 20, y]

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [80]:
np.column_stack((x, 10, 20, y))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

#### np.r_[]

In [81]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [82]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [83]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [84]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [86]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [87]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [88]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [89]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [90]:
np.r_[a, a, a] # concatenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [91]:
np.r_['0', a, a] # concatenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [92]:
np.r_['-1', a, a] # concatenate along last axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [93]:
np.r_['1', a, a] # concatenate along first axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [96]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [99]:
np.r_['0, 2', [1, 2, 3], [4, 5, 6]] # concatenate along first axis, dim>=2

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
np.r_['0, 3', [1, 2, 3], [4, 5, 6]] # concatenate along first axis, dim>=3

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [101]:
arr = np.array([1, 2, 3])
print(arr[np.newaxis, :]) # 0 축으로 차원 증가
print(arr[np.newaxis, :].shape, '\n')
print(arr[:, np.newaxis]) # 1 축으로 차원 증가
print(arr[:, np.newaxis].shape)

[[1 2 3]]
(1, 3) 

[[1]
 [2]
 [3]]
(3, 1)


In [102]:
np.expand_dims(arr, 0)

array([[1, 2, 3]])

In [103]:
np.expand_dims(arr, 1)

array([[1],
       [2],
       [3]])

In [104]:
np.r_[[1, 2, 3], [4, 5, 6]]

array([1, 2, 3, 4, 5, 6])

In [105]:
np.r_['0, 2, 0',  [1, 2, 3],[4, 5, 6]]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [106]:
np.r_['1, 2, 0', [1, 2, 3], [4, 5, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [107]:
np.r_['0, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
np.r_['1, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3, 4, 5, 6]])

In [109]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [111]:
# 축 0과 1로 차원 확장
print(np.expand_dims(a, axis=(0, 1)))
print(np.expand_dims(a, axis=(0, 1)).shape)

[[[1 2 3]]]
(1, 1, 3)


In [113]:
# 축 0과 2로 차원 확장
print(np.expand_dims(a, axis=(0, 2)))
print(np.expand_dims(a, axis=(0, 2)).shape)

[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [114]:
# 축 1과 2로 차원 확장
print(np.expand_dims(a, axis=(1, 2)))
print(np.expand_dims(a, axis=(1, 2)).shape)

[[[1]]

 [[2]]

 [[3]]]
(3, 1, 1)


In [115]:
np.expand_dims(np.array([1, 2, 3]), axis=(1, 2))

array([[[1]],

       [[2]],

       [[3]]])

In [116]:
np.expand_dims(np.array([4, 5, 6]), axis=(1, 2))

array([[[4]],

       [[5]],

       [[6]]])

In [117]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [118]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]].shape

(6, 1, 1)

In [119]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [120]:
print(np.expand_dims(np.array([1, 2, 3]), axis=(0, 2)))
print(np.expand_dims(np.array([4, 5, 6]), axis=(0, 2)))

[[[1]
  [2]
  [3]]]
[[[4]
  [5]
  [6]]]


In [121]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]].shape

(2, 3, 1)

In [122]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [123]:
print(np.expand_dims(np.array([1, 2, 3]), axis=(0, 1)))
print(np.expand_dims(np.array([4, 5, 6]), axis=(0, 1)))

[[[1 2 3]]]
[[[4 5 6]]]


In [124]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]].shape

(2, 1, 3)

#### np.matrix - 시험범위 제외

In [125]:
import numpy as np

a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [126]:
type(a)

numpy.matrix

In [127]:
b = np.matrix([[1, 3], [3, 2]])
b

matrix([[1, 3],
        [3, 2]])

In [128]:
a * b

matrix([[ 7,  7],
        [15, 17]])

In [129]:
a @ b

matrix([[ 7,  7],
        [15, 17]])